[package]
name = "minezweeper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
ggez = "0.9.3"
csv = "1.2.2"
chrono = "0.4.26"
